version: '3.7'
services:
  postgres_db:
    image: postgres
    container_name: live_stream_pg
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=restapi
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=restapi_dev
